# be sure to add all "required" values...

# amazonec2, azure, digitalocean, harvester, vsphere, custom
cloudprovider: harvester

# cloud provider credentials (example: aws-creds)
cloudCredentialSecretName: harvester-creds

# rancher manager url
rancher:
  cattle:
    url: # required (example: rancher.example.com)

# cluster values
cluster:
  # annotations:
    # key: value
  # labels:
    # key: value
  name: rke2-cluster-harvester
  config:
    systemDefaultRegistry: docker.io # default registry
    kubernetesVersion: v1.26.12+rke2r1 # https://github.com/rancher/rke2/releases
    localClusterAuthEndpoint:
      enabled: false
    # agentEnvVars:
      # - key:value
    cni: canal # canal, calico, cilium, multus,canal, multus,calico, multus,cilium
    docker: false
    disable_kube_proxy: false
    etcd_expose_metrics: false
    enableNetworkPolicy: true
    profile: '' # cis-1.6, cis-1.23
    selinux: false
    secrets_encryption: false
    write_kubeconfig_mode: 0600
    use_service_account_credentials: false
    protect_kernel_defaults: false
    cloud_provider_name: '' # aws, azure, harvester, vsphere
    # cloud_provider_config: '' # cloud provider config secret here (example: secret://fleet-default:cloudprovider)
    # kube_controller_manager_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager)
      # - kube controller manager arguments here
    # kube_scheduler_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler)
      # - kube scheduler arguments here
    # kube_apiserver_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver)
      # - kube apiserver arguments here
    # kubelet_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet)
      # - kubelet arguments here
    registries:
      enabled: false
      # configs:
        # - name: registry.example.com
          # authConfigSecretName: registry-creds
          # caBundle: ''
          # insecureSkipVerify: false
          # tlsSecretName: ''
      # mirrors:
        # - name: docker.io
          # endpoints: ['registry.example.com']
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
        # deleteEmptyDirData: true
        # disableEviction: false
        # force: false
        # gracePeriod: -1
        # ignoreDaemonSets: true
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 120
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false
        # deleteEmptyDirData: true
        # disableEviction: false
        # force: false
        # gracePeriod: -1
        # ignoreDaemonSets: true
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 120

# node and nodepool(s) values
nodepools:
  - name: control-plane-nodes
    quantity: 3
    etcd: true
    controlplane: true
    worker: false
    # labels:
      # key: value
    # taints:
      # key: value
    paused: false
    # clusterId: # only needed if not using cloudCredentialSecretName
    # clusterType: # only needed if not using cloudCredentialSecretName
    # kubeconfigContent: # only needed if not using cloudCredentialSecretName
    cpuCount: # required (example: 4)
    # diskBus: virtio
    # diskInfo: ''
    diskSize: # required (example: 64)
    imageName: # required (example: default/image-abcdefg)
    # keyPairName: ''
    memorySize: # required (example: 8)
    # networkInfo: ''
    # networkModel: virtio
    networkName: # required (example: default/default)
    # networkType: ''
    # sshPassword: ''
    # sshPort: 22
    # sshPrivateKeyPath: ''
    sshUser: # required (example: rocky)
    # vmAffinity: ''
    # vmNamespace: default
    # networkData: |
      #cloud-config
    userData: |
      #cloud-config
      package_update: true
      packages: ['qemu-guest-agent']
      runcmd:
      - systemctl enable --now qemu-guest-agent.service

  - name: worker-nodes
    quantity: 3
    etcd: false
    controlplane: false
    worker: true
    # labels:
      # key: value
    # taints:
      # key: value
    paused: false
    # clusterId: # only needed if not using cloudCredentialSecretName
    # clusterType: # only needed if not using cloudCredentialSecretName
    # kubeconfigContent: # only needed if not using cloudCredentialSecretName
    cpuCount: # required (example: 4)
    # diskBus: virtio
    # diskInfo: ''
    diskSize: # required (example: 64)
    imageName: # required (example: default/image-xyz)
    # keyPairName: ''
    memorySize: # required (example: 8)
    # networkInfo: ''
    # networkModel: virtio
    networkName: # required (example: default/default)
    # networkType: ''
    # sshPassword: ''
    # sshPort: 22
    # sshPrivateKeyPath: ''
    sshUser: # required (example: rocky)
    # vmAffinity: ''
    # vmNamespace: default
    # networkData: |
      #cloud-config
    userData: |
      #cloud-config
      package_update: true
      packages: ['qemu-guest-agent']
      runcmd:
      - systemctl enable --now qemu-guest-agent.service

# addons values
addons:
  monitoring:
    enabled: false
    # version:
    # values:
      # values here

  longhorn:
    enabled: false
    # version:
    # values:
      # values here

  neuvector:
    enabled: false
    # version:
    # values:
      # values here
