# be sure to add all "required" values...

# amazonec2, azure, digitalocean, harvester, vsphere, custom
cloudprovider: amazonec2

# cloud provider credentials (example: aws-creds)
cloudCredentialSecretName: aws-creds

# rancher manager url
rancher:
  cattle:
    url: # required (example: rancher.example.com)

# cluster values
cluster:
  # annotations:
    # key: value
  # labels:
    # key: value
  name: rke2-cluster-aws
  config:
    systemDefaultRegistry: docker.io # default registry
    kubernetesVersion: v1.26.11+rke2r1 # https://github.com/rancher/rke2/releases
    localClusterAuthEndpoint:
      enabled: false
    # agentEnvVars:
      # - key:value
    cni: canal # canal, calico, cilium, multus,canal, multus,calico, multus,cilium
    docker: false
    disable_kube_proxy: false
    etcd_expose_metrics: false
    enableNetworkPolicy: true
    profile: '' # cis-1.6, cis-1.23
    selinux: false
    secrets_encryption: false
    write_kubeconfig_mode: 0600
    use_service_account_credentials: false
    protect_kernel_defaults: false
    cloud_provider_name: aws # aws, azure, harvester, vsphere
    # cloud_provider_config: '' # cloud provider config secret here (example: secret://fleet-default:cloudprovider)
    # kube_controller_manager_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager)
      # - kube controller manager arguments here
    # kube_scheduler_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler)
      # - kube scheduler arguments here
    # kube_apiserver_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver)
      # - kube apiserver arguments here
    # kubelet_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet)
      # - kubelet arguments here
    registries:
      enabled: false
      # configs:
        # - name: registry.example.com
          # authConfigSecretName: registry-creds
          # caBundle: ''
          # insecureSkipVerify: false
          # tlsSecretName: ''
      # mirrors:
        # - name: docker.io
          # endpoints: ['registry.example.com']
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
        # deleteEmptyDirData: true
        # disableEviction: false
        # force: false
        # gracePeriod: -1
        # ignoreDaemonSets: true
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 120
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false
        # deleteEmptyDirData: true
        # disableEviction: false
        # force: false
        # gracePeriod: -1
        # ignoreDaemonSets: true
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 120

# node and nodepool(s) values
nodepools:
  - name: control-plane-nodes
    quantity: 3
    etcd: true
    controlplane: true
    worker: false
    # labels:
      # key: value
    # taints:
      # key: value
    paused: false
    # accessKey: # only needed if not using cloudCredentialSecretName
    # secretKey: # only needed if not using cloudCredentialSecretName
    # sessionToken: # only needed if not using cloudCredentialSecretName
    ami: # required (example: ami-123456789)
    # blockDurationMinutes: 0
    deviceName: /dev/sda1
    encryptEbsVolume: false
    # kmsKey: ''
    endpoint: ''
    # httpEndpoint: ''
    # httpTokens: ''
    iamInstanceProfile: # required (example: rancher-iam-instance-profile) - https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon
    insecureTransport: false
    instanceType: # required (example: m5.2xlarge)
    region: # required (example: us-east-1)
    createSecurityGroup: true
    securityGroups: [''] # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements/port-requirements
    # openPort:
    # - "80"
    # - "443"
    keypairName: ''
    securityGroupReadonly: false
    sshKeyContents: ''
    subnetId: # required (example: subnet-123456789)
    zone: # required (example: a)
    monitoring: false
    usePrivateAddress: true
    privateAddressOnly: true
    requestSpotInstance: false
    # spotPrice: ''
    # tags: ''
    retries: 5
    rootSize: 64
    sshUser: ec2-user
    volumeType: gp3
    vpcId: # required (example: vpc-123456789)
    useEbsOptimizedInstance: false
    # userData: |
      #cloud-config

  - name: worker-nodes
    quantity: 3
    etcd: false
    controlplane: false
    worker: true
    # labels:
      # key: value
    # taints:
      # key: value
    paused: false
    # accessKey: '' # only needed if not using cloudCredentialSecretName
    # secretKey: '' # only needed if not using cloudCredentialSecretName
    # sessionToken: '' # only needed if not using cloudCredentialSecretName
    ami: # required (example: ami-123456789)
    # blockDurationMinutes: 0
    deviceName: /dev/sda1
    encryptEbsVolume: false
    # kmsKey: ''
    endpoint: ''
    # httpEndpoint: ''
    # httpTokens: ''
    iamInstanceProfile: # required (example: rancher-iam-instance-profile) - https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon
    insecureTransport: false
    instanceType: # required (example: m5.2xlarge)
    region: # required (example: us-east-1)
    createSecurityGroup: true
    securityGroups: [''] # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements/port-requirements
    # openPort:
    # - "80"
    # - "443"
    keypairName: ''
    securityGroupReadonly: false
    sshKeyContents: ''
    subnetId: # required (example: subnet-123456789)
    zone: # required (example: a)
    monitoring: false
    usePrivateAddress: false
    privateAddressOnly: false
    requestSpotInstance: false
    # spotPrice: ''
    # tags: ''
    retries: 5
    rootSize: 64
    sshUser: ec2-user
    volumeType: gp3
    vpcId: # required (example: vpc-123456789)
    useEbsOptimizedInstance: false
    # userData: |
      #cloud-config

# addons values
addons:
  monitoring:
    enabled: false
    # version:
    # values:
      # values here

  longhorn:
    enabled: false
    # version:
    # values:
      # values here

  neuvector:
    enabled: false
    # version:
    # values:
      # values here
