apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  {{- if .Values.cluster.labels }}
  labels:
{{ toYaml .Values.cluster.labels | indent 4 }}
  {{- end }}
  {{- if .Values.cluster.annotations }}
  annotations:
{{ toYaml .Values.cluster.annotations | indent 4 }}
  {{- end }}
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cluster.config.agentEnvs }}
  agentEnvVars:
{{ toYaml .Values.cluster.config.agentEnvs | indent 4 }}
  {{- end }}
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: cattle-global-data:{{ .Values.cloudCredentialSecretName }}
  {{- end }}
  # clusterAPIConfig:
  # clusterAgentDeploymentCustomization:
  # defaultClusterRoleForProjectMembers:
  # defaultPodSecurityAdmissionConfigurationTemplateName:
  # defaultPodSecurityPolicyTemplateName:
  enableNetworkPolicy: {{ .Values.cluster.config.enableNetworkPolicy | default true }}
  {{- if .Values.cluster.config.kubernetesVersion }}
  # fleetAgentDeploymentCustomization:
  kubernetesVersion: {{ .Values.cluster.config.kubernetesVersion }}
  {{- end }}
  {{- if .Values.cluster.config.localClusterAuthEndpoint }}
  localClusterAuthEndpoint:
    enabled: {{ .Values.cluster.config.localClusterAuthEndpoint.enabled }}
    fqdn: {{ .Values.cluster.config.localClusterAuthEndpoint.fqdn }}
    caCerts: {{ .Values.cluster.config.localClusterAuthEndpoint.caCerts }}
  {{- end }}
  # redeploySystemAgentGeneration:
  rkeConfig:
    # additionalManifest:
    {{- if eq $.Values.cloudprovider "harvester" }}
    chartValues:
      harvester-cloud-provider:
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
        clusterName: {{ .Values.cluster.name }}
    {{- else if eq $.Values.cloudprovider "vsphere" }}
    chartValues:
      rke2-calico: {}
      rancher-vsphere-cpi:
        vCenter:
          host: {{ .Values.vcenter.host }}
          username: {{ .Values.vcenter.username }}
          password: {{ .Values.vcenter.password }}
          labels:
            generate: false
          datacenters: {{ .Values.vcenter.datacenters }}
      rancher-vsphere-csi:
        asyncQueryVolume:
          enabled: true
        csiController:
          csiResizer:
            enabled: true
        improvedVolumeTopology:
          enabled: true
        onlineVolumeExtend:
          enabled: true
        triggerCsiFullsync:
          enabled: true
        vCenter:
          datacenters: {{ .Values.vcenter.datacenters }}
          host: {{ .Values.vcenter.host }}
          username: {{ .Values.vcenter.username }}
          password: {{ .Values.vcenter.password }}
          insecureFlag: {{ .Values.vcenter.skip_tls_verify }}
    {{- else }}
    # chartValues:
    {{- end }}
    # etcd:
    # etcdSnapshotCreate:
    # etcdSnapshotRestore:
    # infrastructureRef:
    machineGlobalConfig:
      cni: {{ .Values.cluster.config.cni | default "canal" }}
      disable-kube-proxy: {{ .Values.cluster.config.disable_kube_proxy | default false }}
      etcd-expose-metrics: {{ .Values.cluster.config.etcd_expose_metrics | default false }}
      profile: {{ .Values.cluster.config.profile }}
      kube-apiserver-arg: {{ .Values.cluster.config.kube_apiserver_arg | toRawJson }}
      kube-scheduler-arg: {{ .Values.cluster.config.kube_scheduler_arg | toRawJson }}
      kube-controller-manager-arg: {{ .Values.cluster.config.kube_controller_manager_arg | toRawJson }}
      kubelet-arg: {{ .Values.cluster.config.kubelet_arg | toRawJson }}
      write-kubeconfig-mode: {{ .Values.cluster.config.write_kubeconfig_mode }}
      use-service-account-credentials: {{ .Values.cluster.config.use_service_account_credentials }}
    # machinePoolDefaults:
    {{- if ne .Values.cloudprovider "custom" }}
    machinePools:
    {{- if .Values.nodepools }} {{ range $index, $nodepool := .Values.nodepools }}
    - controlPlaneRole: {{ $nodepool.controlplane }}
      etcdRole: {{ $nodepool.etcd }}
      workerRole: {{ $nodepool.worker }}
      quantity: {{ $nodepool.quantity }}
      name: {{ $nodepool.name }}
      machineConfigRef:
        {{- if eq $.Values.cloudprovider "amazonec2" }}
        kind: Amazonec2Config
        {{- else if eq $.Values.cloudprovider "vsphere" }}
        kind: VmwarevsphereConfig
        {{- else if eq $.Values.cloudprovider "harvester" }}
        kind: HarvesterConfig
        {{- else if eq $.Values.cloudprovider "digitalocean" }}
        kind: DigitaloceanConfig
        {{- else if eq $.Values.cloudprovider "azure" }}
        kind: AzureConfig
        {{- end}}
        name: {{ $nodepool.name }}
      paused: {{ $nodepool.paused }}
      displayName: {{ $nodepool.displayName }}
      {{- if $nodepool.rollingUpdate }}
      rollingUpdate:
        maxUnavailable: {{ $nodepool.rollingUpdate.maxUnavailable }}
        maxSurge: {{ $nodepool.rollingUpdate.maxSurge }}
      {{- end }}
      {{- if $nodepool.machineDeploymentLabels }}
      machineDeploymentLabels:
{{ toYaml $nodepool.machineDeploymentLabels | indent 8 }}
      {{- end }}
      {{- if $nodepool.machineDeploymentAnnotations }}
      machineDeploymentAnnotations:
{{ toYaml $nodepool.machineDeploymentAnnotations | indent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.nodepool }}
    {{ $nodepool := .Values.nodepool }}
    - controlPlaneRole: {{ $nodepool.controlplane }}
      etcdRole: {{ $nodepool.etcd }}
      workerRole: {{ $nodepool.worker }}
      quantity: {{ $nodepool.quantity }}
      name: {{ $nodepool.name }}
      machineConfigRef:
        {{- if eq $.Values.cloudprovider "amazonec2" }}
        kind: Amazonec2Config
        {{- else if eq $.Values.cloudprovider "vsphere" }}
        kind: VmwarevsphereConfig
        {{- else if eq $.Values.cloudprovider "harvester" }}
        kind: HarvesterConfig
        {{- else if eq $.Values.cloudprovider "digitalocean" }}
        kind: DigitaloceanConfig
        {{- else if eq $.Values.cloudprovider "azure" }}
        kind: AzureConfig
        {{- end}}
        name: {{ $nodepool.name }}
      paused: {{ $nodepool.paused }}
      displayName: {{ $nodepool.displayName }}
      {{- if $nodepool.rollingUpdate }}
      rollingUpdate:
        maxUnavailable: {{ $nodepool.rollingUpdate.maxUnavailable }}
        maxSurge: {{ $nodepool.rollingUpdate.maxSurge }}
      {{- end }}
      {{- if $nodepool.machineDeploymentLabels }}
      machineDeploymentLabels:
{{ toYaml $nodepool.machineDeploymentLabels | indent 8 }}
      {{- end }}
      {{- if $nodepool.machineDeploymentAnnotations }}
      machineDeploymentAnnotations:
{{ toYaml $nodepool.machineDeploymentAnnotations | indent 8 }}
      {{- end }}
    {{- end }}
    {{- if eq $.Values.cloudprovider "harvester" }}
    machineSelectorConfig:
    - config:
        cloud-provider-config: {{ .Values.cloudProviderConfigSecretName }}
        cloud-provider-name: harvester
        {{- if .Values.cluster.config.system_default_registry }}
        system-default-registry: {{ .Values.cluster.config.system_default_registry }}
        {{- end }}
        protect-kernel-defaults: {{ .Values.cluster.config.protect_kernel_defaults | default false }}
        selinux: {{ .Values.cluster.config.selinux | default false }}
    {{- else if eq $.Values.cloudprovider "vsphere" }}
    machineSelectorConfig:
    - config:
        cloud-provider-name: "rancher-vsphere"
        {{- if .Values.cluster.config.system_default_registry }}
        system-default-registry: {{ .Values.cluster.config.system_default_registry }}
        {{- end }}
        docker: false
        protect-kernel-defaults: {{ .Values.cluster.config.protect_kernel_defaults | default false }}
        selinux: {{ .Values.cluster.config.selinux | default false }}
    {{- else }}
    machineSelectorConfig:
    - config:
        cloud-provider-name: ""
        {{- if .Values.cluster.config.system_default_registry }}
        system-default-registry: {{ .Values.cluster.config.system_default_registry }}
        {{- end }}
        docker: false
        protect-kernel-defaults: {{ .Values.cluster.config.protect_kernel_defaults | default false }}
        selinux: {{ .Values.cluster.config.selinux | default false }}
    {{- end }}
    {{- end }}
    # machineSelectorFiles:
    # provisionGeneration:
    {{- if .Values.cluster.config.registries }}
    registries:
{{ toYaml .Values.cluster.config.registries | indent 6 }}
    {{- else }}
    # registries:
    {{- end }}
    # rotateCertificates:
    # rotateEncryptionKeys:
    upgradeStrategy:
      controlPlaneDrainOptions:
        enabled: false
      workerDrainOptions:
        enabled: false
      workerConcurrency: {{ .Values.cluster.config.workerConcurrency | default "10%" }}
      controlPlaneConcurrency: {{ .Values.cluster.config.controlPlaneConcurrency | default "10%" }}